# -*- coding: utf-8 -*-
"""Tema10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BZR6dn4oXhIZWaGr6DHuzdAcq_jbSTn

# Funciones

## Función

**Función.** Una función en `Python` es una pieza de código reutilizable que solo se ejecuta cuando es llamada.

Se define usando la palabra reservada `def` y estructura general es la siguiente:
"""

def nombre_funcion(input1, input2, ..., inputn):
  cuerpo de la función
  return output

"""**Observación.** La instrucción `return` finaliza la ejecución de la función y devuelve el resultado que se indica a continuación. Si no se indicase nada, la función finalizaría, pero no retornaría nada.

Como hemos visto, en general, las funciones constan de 3 partes:

- **Inputs (parámetros o argumentos).** Son los valores que le pasamos como entrada a la función.
- **Cuerpo.** Son todas las operaciones que lleva a cabo la función.
- **Output.** Es el resultado que devuelve la función.

**Observación.** Los parámetros son variables internas de la función. Si probásemos a ejecutar una de dichas variables en el entorno global, nos saltaría un error. Este tema lo trataremos más en detalle más adelante.

Con lo visto anteriormente, a la hora de construir una función hau que hacerse las siguientes preguntas:

- ¿Qué datos necesita conocer la función? (inputs)
- ¿Qué hace la función? (cuerpo)
- ¿Qué devuelve? (output)

**Observación.** Los inputs y el output son opcionales: podemos definir una función sin necesidad de proporcionarle inputs y sin que nos devuelva nada.

Una vez definida una función, para llamarla utilizamos su nombre seguido de paréntesis:
"""

def my_first_function():
    print("Tu primera función te saluda")

my_first_function()

"""Hemos dicho que tanto los inputs como el output son opcionales. Veamos algunos ejemplos con diferentes casos.

---

#### Ejemplo 1

Veamos otro ejemplo que no necesite ningún parámetro y no nos devuelva nada, tal y como ocurría con `my_first_function()`
"""

def hello_world():
  print("Hola mundo!")

hello_world()

"""Nuestra función `hello_world()`, cuando es llamada, imprime "Hola mundo!", pero no devuelve absolutamente nada.

---

#### Ejemplo 2

Veamos un ejemplo de función que no necesita ningún input, pero que devuelve un output. Por ejemplo, una función que nos devuelve "¡Buenos días!"
"""

def good_morning():
    return "Buenos días"

"""Ya hemos declarado la función. Si la llamamos, obtenemos el siguiente resultado:"""

good_morning()

"""Como nos devuelve el saludo, lo podemos guardar en una variable, que será de tipo string"""

goodMorning = good_morning()
print(goodMorning)
print(type(goodMorning))

"""---

#### Ejemplo 3

Veamos ahora un ejemplo de función que no nos devuelva nada, pero que sí toma algún parámetro
"""

def good_morning(name):
  print("¡Buenos días, {}!".format(name))

good_morning(name = "Don Pepito")
good_morning(name = "Don José")

good_morning("María")

"""Ahora nuestra función `good_morning()` recibe como parámetro un nombre y nos muestra por pantalla un "¡Buenos días!" junto con el nombre indicado.

---

#### Ejemplo 4

Por último, vamos a crear una función que nos calcule la división entera de dos números y nos retorne el cociente y el resto.
"""

def euclidean_division(x, y):
  q = x // y
  r = x % y
  return q, r

"""Esta función, a la que hemos llamado `euclidean_division`, calcula el cociente y el resto de dos números cualesquiera y devuelve como resultado esos dos números calculados.

Utilicemos ahora nuestra función para calcular el cociente y el resto de la división $41 \div 7$
"""

euclidean_division(x = 41, y = 7)

euclidean_division(41, 7)

euclidean_division(y = 7, x = 41)

"""Al llamar a la función e indicarle por parámetros `x = 41` e `y = 7`, hemos obtenido como resultado la tupla `(5, 6)`. El significado de dicho resulatdo es que el cociente entero de $41\div 7$ es 5, mientras que el resto es $6$. Efectivamente

$$41 = 7\cdot 5 + 6$$

También podríamos guardar en variables diferentes los resultados que nos devuelve nuestra función, para poder trabajar con ellos en el entorno global
"""

quotient, remainder = euclidean_division(x = 41, y = 7)
print(quotient)
print(remainder)
print(41 == 7 * quotient + remainder)

"""---

## Parámetros

Por defecto, una función debe ser llamada con el número correcto de argumentos. Esto es, si la función espera 2 argumentos, tenemos que llamar a la función con esos 2 argumentos. Ni más, ni menos.
"""

def complete_name(name, surname):
  print("El nombre completo es", name, surname)

complete_name("María", "Santos")

complete_name("Juan Gabriel", "Gomila")

"""Si intentamos llamar a la función `complete_name()` pasando 1 solo parámetro o 3 parámetros, entonces la función devuelve error."""

complete_name(name = "María")

complete_name("Juan", "Gabriel", "Gomila")

"""### Número arbitrario de argumentos

Si no sabemos el número de parámetros que van a ser introducidos, entonces añadimos un asterisco `*` previo al nombre del parámetro en la definición de la función. Los valores introducidos serán guardados en una tupla.
"""

def sum_numbers(*numbers):
  sum = 0
  for n in numbers:
    sum += n

  return sum

sum_numbers(1, 2, 3)

sum_numbers(2, 4, 6, 8, 10)

"""### Número arbitrario de claves de argumento

Hasta ahora hemos visto que al pasar valores por parámetro a la función, podemos hacerlo con la sintaxis `clave_argumento = valor` o directamente pasar por parámetro el valor siguiendo el orden posicional de la definición de la función:
"""

def complete_name(name, surname):
  print("El nombre completo es", name, surname)

complete_name(name = "María", surname = "Santos")

complete_name(surname = "Santos", name = "María")

complete_name("María", "Santos")

"""En realidad, los nombres completos pueden tener dos o incluso más apellidos, pero no sabemos si el usuario tiene 1 o 2 o más. Entones, podemos añadir dos asteriscos `**` antes del nombre del parámetro para así poder introducir tantos como queramos sin que salte error"""

def complete_name(name, **surname):
    print("El nombre completo es {}".format(name), end = " ")
    for i in surname.items():
      print("{}".format(i[1]), end = " ")

complete_name(name = "María", surname1 = "Santos", surname2 = "Fernández")

complete_name(name = "María", surname = "Santos")

"""### Parámetros por defecto

Hemos visto que una función en `Python` puede tener o no parámetros.

En caso de tener, podemos indicar que alguno tenga un valor por defecto.

La función `diff()` calcula la diferencia entre los dos números que introducimos por parámetros. Podemos hacer que el sustraendo por defecto valga 1 del siguiente modo:
"""

def diff(x, y = 1):
  return x - y

diff(65, 18)

"""Si ahora llamamos a la función indicando únicamente el valor del parámetro `x`, ocurre lo siguiente:"""

diff(x = 20)

"""Como resultado hemos obtenido 19, ya que el valor que ha tomado el parámetro `y` ha sido el que le hemos dicho que tome por defecto, es decir, $y = 1$ y, consecuentemente, $x-y = 20-1 = 19$

## Docstring

**Docstring.** Son comentarios explicativos que ayudan a comprender el funcionamiento de una función.

- Van entre triple comilla doble
- Pueden ser multilínea
- Se sitúan al principio de la definición de la función

Retomando el ejemplo de la división entera, podríamos utilizar docstring del siguiente modo:
"""

def euclidean_division(x, y):
  """
  Esta función calcula el cociente y el resto de la
  división entera de x entre y.

  Args:
    x (int): dividendo
    y (int): divisor (que no puede ser cero)

  Returns:
    (q, r): tupla con el valor de (cociente, resto)
  """
  q = x // y
  r = x % y
  return q, r

"""Con la ayuda del método `.__doc__` podemos acceder directamente a la información indicada en el docstring de una función"""

print(euclidean_division.__doc__)

"""## Variables de una función

Dentro de una función en `Python` existen dos tipos de variables:

- **Variable local.** Aquella que es creada y solamente existe dentro de la función.
- **Variable global.** Aquella que es creada en el entorno global.

Dada la siguiente función:
"""

def arithmetic_operations(x, y):
  sum = x + y
  diff = x - y
  prod = x * y
  div = x / y
  return {"sum": sum,
          "difference": diff,
          "product": prod,
          "division": div}

"""Si nosotros queremos imprimir por ejemplo el valor que toma la variable `prod` en el entorno global nos saltará un error, pues esta variable no existe a nivel global porque no ha sido declarada en dicho entorno ya que solamente ha sido declarada a nivel local, dentro de la función `arithmetic_operations()`."""

print(arithmetic_operations(x = 5, y = 3))

print(prod)

"""Si se diese el caso de que sí hubiese sido definida la variable `prod` en el entorno global, como lo que ocurre en el siguiente bloque de código, por mucho que la variable local tenga el mimso nombre y por mucho que ejecutemos la función, el valor de la variable global no se ve modificado"""

prod = 10
print(arithmetic_operations(x = 5, y = 3))
print(prod)

"""Si dentro de una función utilizamos la palabra reservada `global` a una variable local, ésta automáticamente pasa a ser una variable global previamente definida.

Veamos un ejemplo de función que nos devuelve el siguiente número del entero `n` definido en el entorno global:
"""

n = 7

def next_n():
  global n
  return n + 1

next_n()

"""### Paso por copia vs. paso por referencia

Dependiendo del tipo de dato que pasemos por parámetro a la función, podemos diferenciar entre

- **Paso por copia.** Se crea una copia local de la variable dentro de la función.
- **Paso por referencia.** Se maneja directamnete la variable y los cambios realizados dentro de la función afectan también a nivel global.

En general, los tipos de datos básicos como enteros, en coma flotante, strings o booleanos se pasan por copia, mientras que estructuras de datos como listas, diccionarios, conjuntos o tuplas u otros objetos se pasan por referencia.

Un ejemplo de paso por copia sería
"""

def double_value(n):
    n = n*2
    return n

num = 5
print(double_value(num))
print(num)

"""Un ejemplo de paso por referencia sería"""

def double_values(ns):
  for i, n in enumerate(ns):
    ns[i] *= 2

  return ns

nums = [1, 2, 3, 4, 5]
print(double_values(nums))
print(nums)

"""Para evitar la modificación de la lista original, podemos hacerlo introduciendo por parámetro una copia de dicha lista"""

nums = [1, 2, 3, 4, 5]
print(double_values(nums[:]))
print(nums)

"""## Funciones más complejas

Las funciones pueden ser más completas, pues admiten tanto operadores de decisión como de iteración.

Volviendo al ejemplo 4, la función creada claramente es muy sencilla, pues suponemos que el usuario va a introducir por parámetros números enteros.

**Ejercicio.** Mejora la función `euclidean_division()` para que

- Compruebe que los números introducidos son enteros. En caso de no ser así, indicar que se ha tomado la parte entera de los valores introducidos.
- Realice la división entera del mayor parámetro (en valor absoluto) entre el menor parámetro. Esto es, si el usuario introduce `x = -2` e `y = -10`, como 10 > 2, entonces la función debe llevar a cabo la división entera de -10 entre -2.
- Imprima por pantalla una frase indicando la división realizada y el cociente y el resto obtenidos.
- Devuelva el cociente y el resto a modo de tupla

"""

def euclidean_division(x, y):
  ints = (x == int(x)) and (y == int(y))

  if not ints:
    x = int(x)
    y = int(y)
    print("Se tomarán como parámetros la parte entera de los valores introducidos.")

  if abs(x) >= abs(y):
    q = x // y
    r = x % y
    print("Se ha realizado la división {} entre {} y se ha obtenido como cociente q = {} y como resto, r = {}".format(x, y, q, r))

  else:
    q = y // x
    r = y % x
    print("Se ha realizado la división {} entre {} y se ha obtenido como cociente q = {} y como resto, r = {}".format(y, x, q, r))


  return q, r

quotient, remainder = euclidean_division(x = -10.3, y = -5)

-10 == -5 * quotient + remainder

euclidean_division(x = -3, y = 19)

"""---

#### Ejemplo 5

Veamos una función que dado un número, nos dice si éste es positivo, negativo o vale 0.

"""

def sign(num):
  """
  Función que dado un número devuelve el signo positivo,
  negativo o cero del mismo

  Args:
    num (int): número del cual queremos hallar su signo

  Returns:
    signo (string): string positivo, negativo o cero
  """
  if num > 0:
    return "Positivo"
  elif num < 0:
    return "Negativo"
  else:
    return "Cero"

print(sign(num = 3.1415))

print(sign(num = -100))

print(sign(num = 0))

"""---

#### Ejemplo 6

Veamos ahora una función que contiene un bucle `for` y que dado un número entero, nos imprime su tabla de multiplicar con sus 10 primeros múltiplos y nos devuelve una lista con todos esos múltiplos:
"""

def multiplication_table10(num):
  """
  Dado un número entero, imprimimos su tabla de multiplicar con
  los 10 primeros múltiplos y devolvemos una lista de los múltiplos.

  Args:
    num (int): valor del cual vamos a calcular sus tabla de multiplicar

  Returns:
    multiples (list): lista con los 10 primeros múltiplos de num
  """
  multiples = []
  print("La tabla de multiplicar del {}:".format(num))

  for i in range(1, 11):
    multiple = num * i
    print("{} x {} = {}".format(num, i, multiple))
    multiples.append(multiple)

  return multiples

multiples7 = multiplication_table10(num = 7)
print(multiples7)

"""Vamos ahora a mejorar la función `multiplication_table10()` para que si el usuario decide introducir un número que no sea entero, nuestra función le avise y le explique el error que está cometiendo:"""

def multiplication_table10(num):
  """
  Dado un número entero, primero comprovamos si es entero.
  Si no lo es, no devolvemos nada.
  Si lo es, imprimimos su tabla de multiplicar con los 10
  primeros múltiplos y devolvemos una lista de los múltiplos.

  Args:
    num (int): valor del cual vamos a calcular sus 10 primeros múltiplos

  Returns:
    multiples (list): lista con los 10 primeros múltiplos de num
  """

  if type(num) != type(1):
    print("El número introducido no es entero")
    return

  multiples = []
  print("La tabla de multiplicar del {}:".format(num))

  for i in range(1, 11):
    multiple = num * i
    print("{} x {} = {}".format(num, i, multiple))
    multiples.append(multiple)

  return multiples

multiples3 = multiplication_table10(num = 3)
print(multiples3)

multiples_float = multiplication_table10(num = "3.7")
print(multiples_float)

"""---

#### Ejemplo 7

Creemos ahora una función que dada una frase acabada en punto, nos devuelva si contiene o no la letra "a" haciendo uso de un bucle `while`
"""

def contains_a(sentence):
  i = 0
  while sentence[i] != ".":
    if sentence[i] == "a":
      return True
    i += 1
  return False

contains_a("El erizo es bonito.")

contains_a("El elefante es gigante.")

"""**Ejercicio.** Generalizad la función `contains_a()` a una función llamada contains_letter() que devuelva si una frase cualquiera (no necesariamente acabada en punto) contiene o no la letra indicada también por el usuario. Tenéis que hacerlo únicamente con operadores de decisión e iteración. No vale usar ningún método existente de `string`."""

def contains_letter(sentence, letter):
  for c in sentence:
    if c == letter:
      return True
  return False

contains_letter("Mi amigo es muy inteligente, pero un poco pesado", "t")

"""---

## Funciones recursivas

**Función recursiva.** Es una función que se llama a sí misma.

**¡Cuidado!** Hay que tener mucho cuidado con este tipo de funciones porque podemos caer en un bucle infinito. Es decir, que la función no acabara nunca de ejecutarse.

Una función recursiva que entraría en bucle infinito sería la siguiente.
"""

def powers(x, n):
  print(x ** n)
  powers(x, n + 1)

"""¿Por qué decimos que entra en bulce infinito? Pues porque solo parará si nosotros interrumpimos la ejecución.

Esto se debe a que no le hemos indicado un caso de parada a la función, denominado caso final.

**Caso final.** Es el caso que indica cuándo debe romperse la recursión. Hay que indicarlo siempre para no caer en un bucle infinito.

En el caso de la función `powers()`, podemos indicar como caso final cuando el valor resultante supere 1000000. Lo indicamos con un `if`
"""

def powers(x, n):
  if x ** n > 1000000:
    return x ** n

  print(x ** n)
  powers(x, n + 1)

powers(2, 1)

"""---

#### Ejemplo 8

Veamos ahora un ejemplo clásico de función recursiva que funciona correctamente.

Queremos una función que nos imprima el término $i$-ésimo de la sucesión de Fibonacci. Es decir, nosotros le indicamos el índice del término y la función nos devuelve el valor de dicho término.

La sucesión de Fibonacci es

$$1, 1, 2, 3, 5, 8, 13,\dots$$

Es decir, cada término se obtiene de la suma de los dos anteriores.

$$F_0 = F_1 = 1$$
$$F_n = F_{n-1} + F_{n-2}, n\geq 2$$

Con lo cual, la función que queremos y a la que hemos llamado `Fibonacci()` es:

"""

def Fibonacci(index):
  if index == 0 or index == 1:
    return 1

  return Fibonacci(index - 1) + Fibonacci(index - 2)

"""Como veis, le hemos indicado a la función cuando parar. Esto es, el caso final resulta ser cuando el índice vale 0, pues no existen índices negativos."""

Fibonacci(index = 7)

Fibonacci(8)

Fibonacci(30)

"""---

## Funciones helper

Al igual que las funciones pueden llamarse a sí mismas, también pueden llamar a otras funciones.

**Función helper.** Es una función cuyo propósito es evitar la repetición de código.

Si nos dan la siguiente función
"""

def sign_sum(x, y):
  if x + y > 0:
    print("El resultado de sumar {} más {} es positivo".format(x, y))
  elif x + y == 0:
    print("El resultado de sumar {} más {} es cero".format(x, y))
  else:
    print("El resultado de sumar {} más {} es negativo".format(x, y))

sign_sum(5, 4)
sign_sum(3, -3)
sign_sum(1, -8)

"""Vemos que el `print` se repite salvo por la última palabra.

Podríamos pensar en crear la función helper siguiente:
"""

def helper_print(x, y, sign):
  print("El resultado de sumar {} más {} es {}.".format(x, y, sign))

"""Si utilizamos la función helper, la función `sign_sum()` quedaría modificada del siguiente modo:"""

def sign_sum(x, y):
  if x + y > 0:
    helper_print(x, y, "positivo")
  elif x + y == 0:
    helper_print(x, y, "cero")
  else:
    helper_print(x, y, "negativo")

sign_sum(5, 4)
sign_sum(3, -3)
sign_sum(1, -8)

"""Con lo cual ya no hay código repetido.

Y como se puede observar, la función original funciona correctamente.
"""