# -*- coding: utf-8 -*-
"""Tema14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lp3pTJHZ1Zxz7IWMDxv2MLyGlKs1Myg4

# Scripts y Módulos en `Python`

## Scripts

**Script.** Es un archivo que contiene líneas de código. En nuestro caso, dichas líneas estarán escritas con el lenguaje de programación `Python`

Un script de `Python` tiene la extensión `.py`.

Para ejecutar un script de `Python` necesitamos un intérprete como bien puede ser `Spyder`, `Jupyter`, `Google Colab`, ... pero para crearlo nos basta un editor de texto como por ejemplo Text Editor.

### Creando un script de `Python`

En primer lugar, para trabajar con scripts desde Google Drive necesitaremos la aplicación gratuita Text Editor que se consigue en este [link](https://chrome.google.com/webstore/detail/text-editor/gpgjomejfimnbmobcocilppikhncegaj) de la Chrome Web Store.

Una vez descargado, podemos crear un nuevo documento de Text Editor. Lo llamaremos `my_first_script.py` y escribiremos la siguiente línea de código:
"""

print("Mi primer script dice ¡HOLA!")

"""### Importando un script de `Python`

Una vez creado el script, lo guardamos. Una vez guardado, lo podemos importar a este notebook para ejecutarlo.

Para ello, lo primero que haremos será darle al notebook acceso a nuestro drive, pues allí es donde tenemos guardado nuestro script llamado `my_first_script.py`

Al ejecutar la celda, nos saldrá un link que nos llevará a una página de inicio de sesión de nuestra cuenta de Google Drive. Al proporcionar tanto correo como contraseña, se nos proporcionará un código de acceso que tendremos que introducir en la casilla correspondiente. Una vez completado este último paso, ya tendremos configurado Google Drive en nuestro notebook.
"""

from google.colab import drive
drive.mount('/content/drive')

"""A continuación, para poder acceder a nuestro script, necesitamos que la carpeta donde éste esté guardado sea nuestro directorio de trabajo.

Para obtener dicha ruta fácilmente, podemos irnos a Archivos, que se encuentra en el menú lateral izquierdo. Allí podemos ver la carpeta drive, que contiene todos nuestros documentos almacenados en Google Drive. Entonces, navegamos hasta la carpeta en cuestión, en nuestro caso, la carpeta scripts. Hacemos click derecho sobre dicha carpeta y seleccionamos Copiar ruta.

Entonces, para cambiar el directorio de trabajo, ejecutamos la siguiente línea de código, indicando como path el que acabos de copiar.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/python-basico/scripts

"""Ya lo tenemos todo listo para importar nuestro primer script:"""

import my_first_script

"""**¡Cuidado!** Si realizamos algún cambio en el script, no bastará con guardarlo y volver a importar el script. Habrá que reinciar el Kernel y volver a ejecutar todas las líneas de código anteriores: desde la vinculación de Google Drive a nuestro notebook hasta la importación del script.

## Módulos

**Módulo.** Es una librería de código. Es un script que contiene un conjunto de funciones.

Un módulo de `Python`, al ser un script, tiene la extensión `.py`.

Para ejecutar un módulo de `Python` necesitaremos seguir los mismos pasos que cuando trabajábamos con scripts

### Creando un módulo

Hemos dicho que un módulo es un script que contiene funciones. Por tanto, lo primero que hacemos es crear un nuevo documento con Text Editor, al que llamaremos `my_first_module.py`.

En él declararemos las siguientes funciones:
"""

def sum(*numbers):
    """
    Función que suma los elementos que introduzcamos por parámetro
    """
    result = 0
    for n in numbers:
        result += n

    return result

def prod(*numbers):
    """
    Función que multiplica los elementos que introduzcamos por parámetro
    """
    result = 1
    for n in numbers:
        result *= n

    return result

def description():
    print("Este módulo tiene 3 funciones: ")
    print("\t- la que muestra la descripción del módulo")
    print("\t- la que suma los números que introduzcamos por parámetro")
    print("\t- la que multiplica los números que introduzcamos por parámetro")

"""### Importando un módulo de `Python`

Una vez creado el módulo, lo guardamos. Una vez guardado, lo podemos importar a este notebook para ejecutarlo.

Para ello, lo primero que haremos será darle al notebook acceso a nuestro drive.
"""

from google.colab import drive
drive.mount('/content/drive')

"""A continuación, nos aseguramos de que el directorio de trabajo es la carpeta donde tenemos guardado el módulo"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/python-basico/scripts

"""Finalmente, importamos el módulo y accedemos a su función con la siguiente sintaxis"""

import my_first_module

my_first_module.my_description()
total_sum = my_first_module.my_sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total_prod = my_first_module.my_prod(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

print("\nEl resultado de la suma ha sido {} y el del producto, {}".format(total_sum, total_prod))

"""#### Renombrando un módulo

Como recordaréis, cuando vimos por primera vez la palabra reservada `import`, si lo combinábamos con la palabra reservada `as`, conseguíamos renombrar el objeto que importábamos.

En este caso, `my_first_module` es un nombre muy largo. Podemos renombrarlo a `mfm` con la siguiente línea de código, de modo que a partir de ahora cuando queramos invocar alguna función de nuestro módulo, en vez de preceder a cada función por `my_first_module`, lo haremos por `mfm`
"""

import my_first_module as mfm

mfm.my_description()
total_sum = mfm.my_sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total_prod = mfm.my_prod(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

print("\nEl resultado de la suma ha sido {} y el del producto, {}".format(total_sum, total_prod))

"""#### Variables en un módulo

Hasta ahora solo hemos visto como acceder a funciones de un módulo, pero los módulos también pueden contener variables. Añadamos a nuestro módulo las dos siguientes líneas de código:
"""

sum1to10 = my_sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
prod1to10 = my_prod(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

"""**¡Cuidado!** Recordad que si realizamos algún cambio en el script, no bastará con guardarlo y volver a importar el script. Habrá que reinciar el Kernel y volver a ejecutar todas las líneas de código anteriores: desde la vinculación de Google Drive a nuestro notebook hasta la importación del módulo.

Volvemos a importar el módulo, pues hemos reinciado el kernel. Esta vez, solamente vamos a acceder a esas dos nuevas variables: `sum1to10` y `prod1to10`. Y lo hacemos del siguiente modo
"""

import my_first_module as mfm

print("\nEl resultado de la suma de los 10 primeros números enteros es {} y su producto, {}".
      format(mfm.sum1to10, mfm.prod1to10))

"""Si recordáis, cuando vimos la función `import`, observamos que no era necesario importar todo el módulo, sino que podíamos importar funciones o incluso variables concretas del módulo con la sintaxis siguiente, y así evitar tener que indicar el nombre del módulo previo al nombre de la función o la variable en cuestión"""

from my_first_module import sum1to10, prod1to10

"""De modo que el `print` anterior queda modificado del siguiente modo"""

print("\nEl resultado de la suma de los 10 primeros números enteros es {} y su producto, {}".
      format(sum1to10, prod1to10))

"""Finalmente, así como podemos modificar el nombre de los módulos, también podemos modificar el nombre tanto de las funciones como de las variables del módulo:"""

from my_first_module import my_description as mfm_desc
mfm_desc()

"""### Módulos de `Python`

`Python` es un software libre que de por sí ya tiene muchos módulos creados que nos son de mucha utilidad:

- `pandas` para trabajar con dataframes
- `math` para trabajar con funciones y variables matemáticas
- `numpy` para trabajar con elementos numérico
- `matplotlib` para hacer representaciones gráficas

¡Y muchos más!

En secciones futuras veremos en detalle algunos de estos módulos para saber aprovecharlos al máximo.

### La función `dir()`

La función `dir()` aplicada a un script nos devuelve los métodos y las variables que contiene.

Si la aplicamos a nuestro módulo, al que recordad habíamos renombrado como `mfm`, lo que obtenemos es la siguiente lista de métodos y variables.
"""

dir(mfm)

"""**Observación.** Como resultado no solamente hemos obtenido los métodos y las variables creados por nosotros, sino que se muestran algunos atributos extras como `.__file__`, que guarda el path donde está guardado el módulo, que son los que se han creado por defecto y a los cuales también podemos acceder:"""

mfm.__file__